### ISSUE TITLE
Support for Swedish language

### ISSUE THREAD

**Issue by anudsa** [IAmHughes/Multi-Search_German#6]
Hi, I came across this repository and I happened to have used the original script from fluent forever but with some Swedish resources I had found online, I figured I might as well add it here.

**Comment by anudsa** [comment]
I created a new file called swedish.html with links to the Swedish sites:
-Youglish includes pronunciations
-Svenska Akademiens Ordböcker is a list of dictionaries from the Swedish academy
-Glosbe provides translations as well as example sentences
-Korp finds sentences from books, newspapers & similar texts
-Synonymer is somewhat self explanatory

**Comment by IAmHughes** [comment]
Closed in #7
